# Dependencies
markdown:         maruku 
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Wizard Union 
tagline:          'Posts/Notes from time to time.'
description:      "A Programmer's Nonsense. :)"
url:              https://posts.tanki.ninja/
excerpt_separator: <!--more-->
author:
  name:           'Tanki Zhang'
  url:            https://twitter.com/tankiistanki

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/tankijong
